### ISSUE TITLE
It sucks

### ISSUE THREAD

**Issue by RDGames** [mikroprocesorovka/1-projekt-zimni-Betlik#2]
Celá konstrukce není připevněná na pevnou základnu. Kvůli tomu je tento celý projekt nepoužitelný neboť při hýbání se je potřeba konstrukci nepřetržitě držet.

**Comment by Betlik** [comment]
![image](https://user-images.githubusercontent.com/93586784/164991896-0690a107-d5e2-40c2-897f-9ad8d5be46a7.png)

postupujte podle tohoto diagramu
